[package]
name = "tsunoru-worker-core"
version = "0.1.0"
edition = "2024"
publish = false
[lib]
crate-type = ["cdylib", "rlib"]
[features]
default = ["server"]
server = []
[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono-tz = "=0.10.4"
argon2 = { version = "=0.6.0", default-features = false, features = ["alloc", "password-hash"] }
[profile.release]
opt-level = 3
lto = true
